name: Code Runner

on:
  workflow_dispatch:
    inputs:
      message:
        description: A message from Go script
        required: true
        default: "Hello World"

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Show Message
        run: echo "The server sent: ${{ inputs.message }}"