name: Code Runner

on:
  workflow_dispatch:
    inputs:
      language:
        description: Programming language 
        required: true
        default: python 
      source:
        description: Base64-encoded source

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Show Message
        run: |
          echo "The server sent: ${{ inputs.message }}"